#ifndef __IPANEL_CONFIG_H__
#define __IPANEL_CONFIG_H__


#define DEBUG_LEVEL     7
#define HAVE_PAGE_MULTI_DISPMODE
#define OPTION_BLACK_BACKGROUND
#define OPTION_HISTORY_FOCUS
#define USE_APP_MANAGER
#define USE_CA
#define USE_CA_TYPE     VANE_CA_TYPE_CD
#define USE_CNTV_PLAYER
#define USE_DEVICE_MODULE
#define USE_DVB_DOWNLOAD_SKIN
#define USE_DVB_MODULE
#define USE_HTML_FILTER
#define USE_INPUT_METHOD_V2
#define USE_IP_DOWNLOAD_SKIN
#define USE_IP_NETWORK
#define USE_KVM
#define USE_LAN_CONNECTION
#define USE_MP3_MODULE
#define USE_NETWORK_MANAGER
#define USE_SINO_UNICODE_FONT_COMPATIBLE
#define USE_SOUND_EFFECT
#define USE_SSL_MODULE
#define USE_STOCK
#define USE_STOCK_VERSION     STOCK_VERSION_3
#define USE_TTS_TYPE     TTS_TYPE_KEDA_MSP
#define USE_VOD_MODULE
#define USE_VOD_TYPE     VANE_VOD_TYPE_SEACHANGE_V2
#define USE_WEBCORE_PROFESSIONAL
#define USE_WPI_FONT_TYPE     VANE_FONT_TYPE_SINOFONT
#define Z_MACROCCSCM_1301476932
#define Z_MACROCCSCM_1301477398
#define Z_MACROCCSCM_1301479439
#define Z_MACROCCSCM_1301535739
#define Z_MACROCCSCM_1301649567
#define Z_MACROCCSCM_1301650253
#define Z_MACROCCSCM_1304132316
/* 以“Z_MACROCCSCM”开头的宏只做配置显示，对编译没影响 */

#endif /* __IPANEL_CONFIG_H__ */

